---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  # - ./sonarr/ks.yaml
  - ./recyclarr/ks.yaml
  # - ./autobrr/ks.yaml
  # - ./speedtest-exporter/ks.yaml
